CREATE DATABASE test;
use test;
CREATE TABLE author (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, count_books INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE book (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) NOT NULL, image LONGBLOB NOT NULL, year_public INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB);
        INSERT INTO author(name,count_books) VALUES ('Иванов Иван Петрович', 0));
        INSERT INTO author(name,count_books) VALUES ('Иванов Ивана Петровна', 0));
        INSERT INTO author(name,count_books) VALUES ('Иванович Иван Петровичввв', 0));
        INSERT INTO book(name,description,image,year_public) VALUES ('Золушка\','Из мультфильма','', 1996));
        INSERT INTO book(name,description,image,year_public) VALUES ('Трое из Лас-Вегаса','Из мультфильма','', 1997));
        INSERT INTO book(name,description,image,year_public) VALUES ('Побез из замка','Из мультфильма\','', 2022));
        CREATE TABLE author_books (book_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_5C930A5F16A2B381 (book_id), INDEX IDX_5C930A5FF675F31B (author_id), PRIMARY KEY(book_id, author_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB);
        ALTER TABLE author_books ADD CONSTRAINT FK_5C930A5F16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE ON UPDATE CASCADE );
        ALTER TABLE author_books ADD CONSTRAINT FK_5C930A5FF675F31B FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE );
